compute_environment: LOCAL_MACHINE
debug: false
distributed_type: FSDP
downcast_bf16: "no"
machine_rank: 0
main_training_function: main
mixed_precision: fp8
num_machines: 1
num_processes: 4
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false

fsdp_config:
  fsdp_version: 2
  fsdp_cpu_ram_efficient_loading: false
  fsdp_use_orig_params: true
  fsdp_sync_module_states: true
  fsdp_forward_prefetch: false
  fsdp_sharding_strategy: NO_SHARD
  fsdp_state_dict_type: FULL_STATE_DICT
